name: Run samples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-samples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Get yq
        run: wget https://github.com/mikefarah/yq/releases/download/v4.25.2/yq_linux_amd64.tar.gz -O - | tar xz && sudo mv yq_linux_amd64 /usr/bin/yq

      - name: Install deps
        run: sudo apt install graphviz

      - name: Test Samples
        run: ./test-samples.sh

      - name: Archive artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            /tmp/t.png
